server:
  port: 8083
spring:
  application:
    name: Dealer-App
  data:
    mongodb:
      uri: mongodb+srv://utronics:test@utronics.i4evz.mongodb.net/CropDealDealer?retryWrites=true&w=majority
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
